name: presentation_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  keybord_input:
    path: ../keybord_input  

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  fonts:
    - family: MPLUS1
      fonts:
        - asset: assets/fonts/MPLUS1-VariableFont_wght.ttf
        - asset: assets/fonts/MPLUS1-Black.ttf
          weight: 900
        - asset: assets/fonts/MPLUS1-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MPLUS1-Bold.ttf
          weight: 700
        - asset: assets/fonts/MPLUS1-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MPLUS1-Medium.ttf
          weight: 500
        - asset: assets/fonts/MPLUS1-Regular.ttf
          weight: 400
        - asset: assets/fonts/MPLUS1-Light.ttf
          weight: 300
        - asset: assets/fonts/MPLUS1-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/MPLUS1-Thin.ttf
          weight: 100
                                      